export const PRODUCTS = [
  {
    category: "Phones & Tablets",
    name: "Itel A70",
    spec: "128GB + 4GB",
    monthly: 16.41,
    page: 21,
  },
  {
    category: "Phones & Tablets",
    name: "Itel Vista Tab 10",
    spec: "128GB + 4GB",
    monthly: 20.56,
    page: 22,
  },
  {
    category: "Phones & Tablets",
    name: "Tecno Tablet",
    spec: "256GB + 4GB",
    monthly: 22.97,
    page: 23,
  },
  {
    category: "Phones & Tablets",
    name: "Tecno Pop 8",
    spec: "64GB + 4GB",
    monthly: 14.48,
    page: 24,
  },
  {
    category: "Phones & Tablets",
    name: "Tecno Pop 9",
    spec: "128GB + 4GB",
    monthly: 18.34,
    page: 25,
  },
  {
    category: "Phones & Tablets",
    name: "Tecno Pop 10",
    spec: "128GB + 4GB",
    monthly: 19.79,
    page: 26,
  },
  {
    category: "Phones & Tablets",
    name: "Tecno Camon 40",
    spec: "128GB + 8GB",
    monthly: 28.96,
    page: 27,
  },
  {
    category: "Phones & Tablets",
    name: "Tecno Camon 40",
    spec: "256GB + 8GB",
    monthly: 29.92,
    page: 28,
  },
  {
    category: "Phones & Tablets",
    name: "Redmi 13C",
    spec: "128GB + 4GB",
    monthly: 16.41,
    page: 31,
  },
  {
    category: "Phones & Tablets",
    name: "Redmi A5",
    spec: "128GB + 4GB",
    monthly: 14.48,
    page: 32,
  },
  {
    category: "Phones & Tablets",
    name: "Redmi 14C",
    spec: "128GB + 4GB",
    monthly: 20.56,
    page: 33,
  },
  {
    category: "Phones & Tablets",
    name: "Kids Tablet",
    spec: "64GB + 2GB",
    monthly: 14.48,
    page: 34,
  },
  {
    category: "Phones & Tablets",
    name: "Galaxy A06",
    spec: "128GB + 4GB",
    monthly: 18.53,
    page: 35,
  },
  {
    category: "Phones & Tablets",
    name: "Galaxy A16",
    spec: "128GB + 4GB",
    monthly: 23.17,
    page: 36,
  },
  {
    category: "Phones & Tablets",
    name: "Galaxy F06",
    spec: "128GB + 4GB",
    monthly: 19.6,
    page: 37,
  },
  {
    category: "Phones & Tablets",
    name: "Galaxy M15",
    spec: "128GB + 4GB",
    monthly: 21.43,
    page: 38,
  },
  {
    category: "Kitchen Appliances",
    name: "Russell Hobbs Pressure Cooker",
    spec: "",
    monthly: 23.17,
    page: 41,
  },
  {
    category: "Kitchen Appliances",
    name: "Air Fryer",
    spec: "",
    monthly: 23.17,
    page: 42,
  },
  {
    category: "Kitchen Appliances",
    name: "Superior 2 Plate Gas Stove + Gas Tank",
    spec: "",
    monthly: 9.17,
    page: 43,
  },
  {
    category: "Kitchen Appliances",
    name: "MCK Gas Combo",
    spec: "",
    monthly: 12.07,
    page: 44,
  },
  {
    category: "Kitchen Appliances",
    name: "Superior Gas and Electric Combo",
    spec: "",
    monthly: 34.94,
    page: 45,
  },
  {
    category: "Kitchen Appliances",
    name: "Superior 4 Plate Gas Stove",
    spec: "",
    monthly: 30.89,
    page: 46,
  },
  {
    category: "Kitchen Appliances",
    name: "Superior Princess 4 Plate Electric Stove",
    spec: "",
    monthly: 52.12,
    page: 47,
  },
  {
    category: "Kitchen Appliances",
    name: "Defy 30L Microwave",
    spec: "",
    monthly: 23.65,
    page: 57,
  },
  
  {
    category: "Home Furniture",
    name: "Restapedic Double Bed",
    spec: "",
    monthly: 32.14,
    page: 58,
  },
  {
    category: "Home Furniture",
    name: "Restapedic Queen Bed",
    spec: "",
    monthly: 35.04,
    page: 52,
  },
  {
    category: "Home Furniture",
    name: "Restapedic King Size",
    spec: "",
    monthly: 48.26,
    page: 53,
  },
  {
    category: "Home Furniture",
    name: "2 Door Wardrobe",
    spec: "",
    monthly: 25.58,
    page: 54,
  },
  {
    category: "Home Furniture",
    name: "3 Door Wardrobe (Custom)",
    spec: "",
    monthly: 40.54,
    page: 55,
  },
  {
    category: "Home Furniture",
    name: "5 Door Wardrobe (Custom)",
    spec: "",
    monthly: 53.09,
    page: 56,
  },
  {
    category: "Computers, Accessories & TVs",
    name: "Oraimo 27K Powerbank",
    spec: "",
    monthly: 8.3,
    page: 61,
  },
  {
    category: "Computers, Accessories & TVs",
    name: "Oraimo 50K Powerbank",
    spec: "",
    monthly: 10.14,
    page: 62,
  },
  {
    category: "Computers, Accessories & TVs",
    name: "HP Mini Laptop (TouchScreen)",
    spec: "",
    monthly: 24.13,
    page: 63,
  },
  {
    category: "Computers, Accessories & TVs",
    name: "HP Laptop + Printer",
    spec: "",
    monthly: 47.3,
    page: 64,
  },
  {
    category: "Computers, Accessories & TVs",
    name: "HP Laptop",
    spec: "",
    monthly: 37.65,
    page: 65,
  },
  {
    category: "Computers, Accessories & TVs",
    name: "Epson Ecotank Printer",
    spec: "",
    monthly: 27.99,
    page: 66,
  },
  {
    category: "Computers, Accessories & TVs",
    name: "Hisense 50 Inches Smart TV",
    spec: "50-inch",
    monthly: 65.64,
    page: 51,
  },
  {
    category: "Computers, Accessories & TVs",
    name: "Hisense 32 Inch Smart TV",
    spec: "32-inch",
    monthly: 23.17,
    page: 67,
  },
  {
    category: "Computers, Accessories & TVs",
    name: "Hisense 43 Inch Smart TV",
    spec: "43-inch",
    monthly: 42.47,
    page: 68,
  },
  {
    category: "Fridges & Freezers",
    name: "Capri 210L Chest Freezer",
    spec: "210L",
    monthly: 38.9,
    page: 71,
  },
  {
    category: "Fridges & Freezers",
    name: "Capri 270L Chest Freezer",
    spec: "270L",
    monthly: 43.92,
    page: 72,
  },
  {
    category: "Fridges & Freezers",
    name: "Capri 320L Chest Freezer",
    spec: "320L",
    monthly: 49.23,
    page: 73,
  },
  {
    category: "Fridges & Freezers",
    name: "Capri Bar Fridge",
    spec: "",
    monthly: 34.94,
    page: 74,
  },
  {
    category: "Fridges & Freezers",
    name: "Capri 290L Upright Fridge",
    spec: "290L",
    monthly: 46.72,
    page: 75,
  },
  {
    category: "Fridges & Freezers",
    name: "Capri 350L Fridge Top Freezer",
    spec: "350L",
    monthly: 54.25,
    page: 76,
  },
  {
    category: "Fridges & Freezers",
    name: "Capri 370L Fridge Top Freezer",
    spec: "370L",
    monthly: 59.17,
    page: 77,
  },
  {
    category: "Fridges & Freezers",
    name: "Capri 390L Fridge Top Freezer",
    spec: "390L",
    monthly: 61.78,
    page: 78,
  },
  {
    category: "Solar Products",
    name: "Sunking PRO 2 Solar Light",
    spec: "",
    monthly: 6.76,
    page: 81,
  },
  {
    category: "Solar Products",
    name: "Sunking Home 60 Solar Light",
    spec: "",
    monthly: 16.22,
    page: 81,
  },
  {
    category: "Solar Products",
    name: "1.5Kv Lithium Solar Generator",
    spec: "",
    monthly: 60.81,
    page: 82,
  },
  {
    category: "Solar Products",
    name: "1.1Kv Gel Solar Generator",
    spec: "",
    monthly: 48.26,
    page: 83,
  },
  {
    category: "Solar Products",
    name: "Sunking Home Plus Pro",
    spec: "",
    monthly: 16.22,
    page: 84,
  },
  {
    category: "Solar Products",
    name: "Sunking Home 120+",
    spec: "5 lights",
    monthly: 20.27,
    page: 85,
  },
  {
    category: "Solar Products",
    name: "330 Watts S/Panel",
    spec: "",
    monthly: 16.89,
    page: 86,
  },
  {
    category: "Solar Products",
    name: "450 Watts S/Panel",
    spec: "",
    monthly: 19.79,
    page: 87,
  },
  {
    category: "Power & Batteries",
    name: "550 Watts S/Panel",
    spec: "",
    monthly: 27.03,
    page: 91,
  },
  {
    category: "Power & Batteries",
    name: "100Ah Exide Solar Battery",
    spec: "100Ah",
    monthly: 27.03,
    page: 92,
  },
  {
    category: "Power & Batteries",
    name: "628/9 CC",
    spec: "",
    monthly: 11.97,
    page: 93,
  },
  {
    category: "Power & Batteries",
    name: "642/3 CC",
    spec: "",
    monthly: 16.12,
    page: 94,
  },
  {
    category: "Power & Batteries",
    name: "630/1 CC",
    spec: "",
    monthly: 10.42,
    page: 95,
  },
  {
    category: "Power & Batteries",
    name: "622/3 CC",
    spec: "",
    monthly: 11.97,
    page: 96,
  },
  {
    category: "Power & Batteries",
    name: "638/9 CC",
    spec: "",
    monthly: 13.51,
    page: 97,
  },
  {
    category: "Power & Batteries",
    name: "650/1 CC",
    spec: "",
    monthly: 15.64,
    page: 98,
  },
];

export const CATEGORIES = [
  "All",
  ...new Set(PRODUCTS.map((product) => product.category)),
];

export function whatsappUrl(message) {
  return `https://wa.me/263713756610?text=${encodeURIComponent(message)}`;
}

export function productMessage(product) {
  return `Hello HomeGoods, I'm interested in ${product.name}${product.spec ? ` (${product.spec})` : ""} Please tell me how to apply.`;
}
